### ISSUE TITLE
Create website

### ISSUE THREAD

**Issue by dismantl** [dismantl/CaseHarvester#7]
We need a basic web presence describing the Case Harvester project, including mission, available data, how to contribute, how to report issues or give feedback, and info for researchers and journalists who want to access our database.

Down the line we would like to add sample analyses and visualizations, and also custom search functionality.

**Comment by not-napoleon** [comment]
I've used Jekyll (https://jekyllrb.com/) for building static sites before, and it's pretty low overhead.  You can write pages in markdown, or use a plugin for lots of other formatting languages, and you can have headers & footers, themes, shared data, etc.  Then it builds all of that into static html files that you can just stick on a web server or in s3.  It's also the tool that powers github pages, so if we wanted to use that as a server, we have that option.

Anyway, if that sounds like something you'd like to use, I could get something set up for a starting point.

**Comment by dismantl** [comment]
I think using Jekyll for an initial info-only site would be a great option. I wouldn't want to use it for a website that we'd want non-tech folks updating on the regular, since learning markdown can be a pain. But at this point, some static info about the project is really all we need. So I say go for it! Thanks!

**Comment by dismantl** [comment]
I also like the idea of hosting it on Github pages, so we can potentially tie it to the code repo. My only question is what a good domain would be. It seems like unless you use a custom domain, Github pages only allows you to use your username or org name (e.g. myorg.github.io), but it would be best to have the domain specific to the Case Harvester project. Thoughts on that?

**Comment by not-napoleon** [comment]
Github pages is easy, but it's also a little limited.  It's directly tied to the github account (not the project), and needs to be in a dedicated repo with the magic name <username>.github.io, so you can't keep the web page in the same repo as the project.  If we create a team for this project, that would be a good place to use github pages.  That said, it's very easy to set up - you just push to master in that repo and it updates the site.  You can read more here: https://pages.github.com/

The other low effort solution is to set up on s3 static hosting: https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html This seems pretty easy, although I have never set it up myself.

Both options support using a custom domain name, with a little tinkering.

**Comment by dismantl** [comment]
Ok gotcha. Well I'd say at this point go ahead and create a static site with Jekyll and we'll figure out the hosting/domain situation when it's time. 

Is there any language for the site I can provide?
